version: 2

project_name: remilia

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/bot
    env:
      - CGO_ENABLED=1
    ldflags:
      - -s -w -X github.com/KomeiDiSanXian/remilia.Version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore"

dockers:
  - image_templates:
      - "ghcr.io/KomeiDiSanXian/remilia:{{ .Version }}"
      - "ghcr.io/KomeiDiSanXian/remilia:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

release:
  github:
    owner: KomeiDiSanXian
    name: remilia
  prerelease: auto
  make_latest: true
