apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: remilia-data
  namespace: remilia
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard
