apiVersion: v1
kind: Service
metadata:
  name: remilia-bot
  namespace: remilia
  labels:
    app: remilia-bot
spec:
  type: ClusterIP
  selector:
    app: remilia-bot
  ports:
    - name: webhook
      port: 8080
      targetPort: webhook
      protocol: TCP
    - name: health
      port: 9001
      targetPort: health
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: remilia-bot-headless
  namespace: remilia
  labels:
    app: remilia-bot
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: remilia-bot
  ports:
    - name: health
      port: 9001
      targetPort: health
